tag-prefix: v

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

categories:
  - title: Features
    labels:
      - feat
      - perf
  - title: Bug Fixes
    labels:
      - bug
      - fix
  - title: Documentation
    labels:
      - docs
  - title: Maintenance
    labels:
      - build
      - ci
      - refactor
      - style
      - test

template: |
  # Changes

  $CHANGES
