FROM node:slim

WORKDIR /blokmap-frontend

ARG VITE_MAPBOX_API_KEY

COPY package.json package-lock.json ./

RUN npm install -g npm
RUN npm install

COPY . .

RUN VITE_MAPBOX_API_KEY=$VITE_MAPBOX_API_KEY npm run build -- --mode production
