name: Common nodejs steps
description: Runs common steps used in nodejs workflows

runs:
    using: composite
    steps:
      - name: Set up node
        uses: actions/setup-node@v4
        with:
            node-version: "latest"
            cache: "npm"

      - name: Install dependencies
        run: npm install --save-dev
        shell: bash

