import type { Institution } from '@/types/model/Institution';

export const mockInstitutions: Institution[] = [
    {
        slug: {
            nl: 'UGent',
            en: 'UGent',
            de: 'UGent',
            fr: 'UGent',
        },
        name: {
            nl: 'Universiteit Gent',
            en: 'Ghent University',
            de: 'Universität Gent',
            fr: 'Université de Gand',
        },
        logo: { url: 'https://www.ugent.be/logo.png' },
        email: 'info@ugent.be',
        phone: '09 331 01 01',
        street: 'Sint-Pietersnieuwstraat 33',
        zip: '9000',
        city: 'Gent',
        province: 'Oost-Vlaanderen',
        country: 'België',
    },
    {
        slug: {
            nl: 'KU Leuven',
            en: 'KU Leuven',
            de: 'KU Leuven',
            fr: 'KU Leuven',
        },
        name: {
            nl: 'Katholieke Universiteit Leuven',
            en: 'Catholic University of Leuven',
            de: 'Katholische Universität Löwen',
            fr: 'Université catholique de Louvain',
        },
        logo: { url: 'https://stijl.kuleuven.be/releases/latest/img/svg/logo.svg' },
        email: 'info@kuleuven.be',
        phone: '016 32 40 10',
        street: 'Oude Markt 13',
        zip: '3000',
        city: 'Leuven',
        province: 'Vlaams-Brabant',
        country: 'België',
    },
    {
        slug: {
            nl: 'VUB',
            en: 'VUB',
            de: 'VUB',
            fr: 'VUB',
        },
        name: {
            nl: 'Vrije Universiteit Brussel',
            en: 'Free University of Brussels',
            de: 'Freie Universität Brüssel',
            fr: 'Université libre de Bruxelles',
        },
        logo: {
            url: 'https://www.vub.be/themes/custom/ocelot_vub/assets/vectors/vub-logo-icon.svg',
        },
        email: 'info@vub.be',
        phone: '+32 2 629 20 10',
        street: 'Pleinlaan 2',
        zip: '1050',
        city: 'Elsene',
        province: 'Brussel',
        country: 'België',
    },
    {
        slug: {
            nl: 'UAntwerpen',
            en: 'UAntwerpen',
            de: 'UAntwerpen',
            fr: 'UAntwerpen',
        },
        name: {
            nl: 'Universiteit Antwerpen',
            en: 'University of Antwerp',
            de: 'Universität Antwerpen',
            fr: 'Université d’Anvers',
        },
        logo: {
            url: 'https://www.uantwerpen.be/img/logo-nl.svg',
        },
        email: 'info@uantwerpen.be',
        phone: '+ 32(0)3 265 41 11',
        street: 'Prinsstraat 13',
        zip: '2000',
        city: 'Antwerpen',
        province: 'Antwerpen',
        country: 'België',
    },
    {
        slug: {
            nl: 'HOGent',
            en: 'HOGent',
            de: 'HOGent',
            fr: 'HOGent',
        },
        name: {
            nl: 'Hogeschool Gent',
            en: 'Ghent University of Applied Sciences and Arts',
            de: 'Hogeschool Gent',
            fr: 'Hogeschool Gent',
        },
        logo: {
            url: 'https://www.hogent.be/themes/hogent/assets/images/HOGENT_Logo.png',
        },
        email: 'info@hogent.be',
        phone: '09 243 33 33',
        street: 'Geraard de Duivelstraat 5',
        zip: '9000',
        city: 'Gent',
        province: 'Oost-Vlaanderen',
        country: 'België',
    },
    {
        slug: {
            nl: 'Howest',
            en: 'Howest',
            de: 'Howest',
            fr: 'Howest',
        },
        name: {
            nl: 'Hogeschool West-Vlaanderen',
            en: 'University of Applied Sciences West Flanders',
            de: 'Hogeschool West-Vlaanderen',
            fr: 'Hogeschool West-Vlaanderen',
        },
        logo: {
            url: 'https://www.howest.be/fs/logo/howest.svg',
        },
        email: 'info@howest.be',
        phone: '+32 50 68 26 66',
        street: 'Marksesteenweg 58',
        zip: '8500',
        city: 'Kortrijk',
        province: 'West-Vlaanderen',
        country: 'België',
    },
    {
        slug: {
            nl: 'Arteveldehogeschool',
            en: 'Artevelde University of Applied Sciences',
            de: 'Arteveldehogeschool',
            fr: 'Arteveldehogeschool',
        },
        name: {
            nl: 'Arteveldehogeschool',
            en: 'Artevelde University of Applied Sciences',
            de: 'Arteveldehogeschool',
            fr: 'Arteveldehogeschool',
        },
        logo: {
            url: 'https://ahscdn.be/themes/custom/calibr8_easytheme/logo.svg',
        },
        email: 'info@arteveldehogeschool.be',
        phone: '09 234 90 00',
        street: 'Hoogpoort 15',
        zip: '9000',
        city: 'Gent',
        province: 'Oost-Vlaanderen',
        country: 'België',
    },
    {
        slug: {
            nl: 'Odisee',
            en: 'Odisee',
            de: 'Odisee',
            fr: 'Odisee',
        },
        name: {
            nl: 'Odisee Hogeschool',
            en: 'Odisee University of Applied Sciences',
            de: 'Odisee Hochschule',
            fr: 'Hogeschool Odisee',
        },
        logo: {
            url: 'https://www.odisee.be/themes/custom/odisee/dist/img/logos/logo-nl.svg',
        },
        email: 'kcgezinswetenschappen@odisee.be',
        phone: '+32 (0)2 240 68 40',
        street: 'Huart Hamoirlaan 136',
        zip: 'B-1030',
        city: 'Brussel',
        province: 'Brussel',
        country: 'België',
    },
    {
        slug: {
            nl: 'Thomas More',
            en: 'Thomas More',
            de: 'Thomas More',
            fr: 'Thomas More',
        },
        name: {
            nl: 'Thomas More Hogeschool',
            en: 'Thomas More University of Applied Sciences',
            de: 'Thomas More Hochschule',
            fr: 'Hogeschool Thomas More',
        },
        logo: {
            url: 'https://www.thomasmore.be/themes/custom/tm/assets/images/logo/thomasmore_logo_oranje.svg',
        },
        email: 'info@thomasmore.be',
        phone: '014 56 23 10',
        street: 'Kleinhoefstraat 4',
        zip: '2440',
        city: 'Geel',
        province: 'Antwerpen',
        country: 'België',
    },
];
