name: Build, publish, and deploy new images

permissions:
    packages: write
    contents: read

on:
    push:
        tags: ["v*"]

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml

    create-release-draft:
        runs-on: self-hosted
        needs: ci
        permissions:
            contents: write
        steps:
          - uses: release-drafter/release-drafter@v6
            with:
                config-name: release-drafter.yaml
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release:
        runs-on: self-hosted
        needs: ci
        steps:
          - name: Load docker metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: |
                    ghcr.io/blokmap/blokmap-frontend
                tags: |
                    type=semver,pattern={{version}}

          - name: Login to GHCR
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push
            uses: docker/build-push-action@v6
            env:
                VITE_MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
            with:
                file: Dockerfile.staging
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                cache-from: type=registry,ref=ghcr.io/blokmap/blokmap-frontend:buildcache
                cache-to: type=registry,ref=ghcr.io/blokmap/blokmap-frontend:buildcache,mode=max

    deploy:
        runs-on: self-hosted
        needs: [release]
        steps:
          - name: Deploy frontend
            uses: appleboy/ssh-action@v1.2.1
            with:
                host: ${{ secrets.PRODUCTION_HOST }}
                username: ${{ secrets.PRODUCTION_USERNAME }}
                key: ${{ secrets.PRODUCTION_SSH_KEY }}
                debug: true
                script: |
                    set -e
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml up blokmap-staging-frontend
