name: Lint and format code

on:
    push

jobs:
    lint-and-format:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up node
            uses: actions/setup-node@v4
            with:
                node-version: "latest"
                cache: "npm"

          - name: Install dependencies
            run: npm install --save-dev

          - name: Lint code
            run: npm run lint:fix

          - name: Format code
            run: npm run format
