name: Build and release a new docker image and deploy new assets

permissions:
    packages: write

on:
    push:
        tags: ["v*"]

jobs:
    lint-and-test:
        uses: ./.github/workflows/lint-and-test.yaml

    release:
        runs-on: ubuntu-latest
        needs: lint-and-test
        steps:
          - name: Load docker metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: |
                    ghcr.io/blokmap/blokmap-backend
                tags: |
                    type=semver,pattern={{version}}

          - name: Login to GHCR
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push
            uses: docker/build-push-action@v6
            with:
                file: Dockerfile.prod
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                cache-from: type=registry,ref=ghcr.io/blokmap/blokmap-backend:buildcache
                cache-to: type=registry,ref=ghcr.io/blokmap/blokmap-backend:buildcache,mode=max

    deploy:
        runs-on: self-hosted
        needs: [release]
        steps:
          - name: Deploy frontend
            uses: appleboy/ssh-action@v1.2.1
            with:
                host: ${{ secrets.PRODUCTION_HOST }}
                username: ${{ secrets.PRODUCTION_USERNAME }}
                key: ${{ secrets.PRODUCTION_SSH_KEY }}
                debug: true
                script: |
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml pull
                    docker compose -f /home/blokmap/deploy/production/compose.staging.yaml up blokmap-staging-frontend
