name: Lint, format, and test code

on:
    push

jobs:
    lint-and-format:
        runs-on: self-hosted

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup
            uses: ./.github/actions/common

          - name: Lint code
            run: npm run lint:fix

          - name: Format code
            run: npm run format

    unit-tests:
        runs-on: self-hosted

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup
            uses: ./.github/actions/common

          - name: Run unit tests
            run: npm run test:unit

    e2e-tests:
        runs-on: self-hosted

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup
            uses: ./.github/actions/common

          - name: Run e2e tests
            run: npm run test:e2e
