name: Test code

on:
    push

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up node
            uses: actions/setup-node@v4
            with:
                node-version: "latest"
                cache: "npm"

          - name: Install dependencies
            run: npm install --save-dev

          - name: Run unit tests
            run: npm run test:unit

    e2e-tests:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up node
            uses: actions/setup-node@v4
            with:
                node-version: "latest"
                cache: "npm"

          - name: Install dependencies
            run: npm install --save-dev

          - name: Run e2e tests
            run: npm run test:e2e
